package ElasticPL;
/* Generated By:JJTree: Do not edit this line. ASTFinalBountyCheckExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFinalBountyCheckExpression extends SimpleNode {
  public ASTFinalBountyCheckExpression(int id) {
    super(id);
  }

  public ASTFinalBountyCheckExpression(ElasticPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a3f8ce40b1d2512d6a73aca1219d57e (do not edit this line) */
