package ElasticPL;
/* Generated By:JJTree: Do not edit this line. ASTReadStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReadStatement extends SimpleNode {
  public ASTReadStatement(int id) {
    super(id);
  }

  public ASTReadStatement(ElasticPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b6fa7094ccc9a9771b9d370d8a923cd (do not edit this line) */
