package ElasticPL;
/* Generated By:JavaCC: Do not edit this line. ElasticPLParserTreeConstants.java Version 6.0_1 */
public interface ElasticPLParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTINPUTSPECIFICATIONSTATEMENT = 1;
  public int JJTVERIFYSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTASSIGNMENT = 4;
  public int JJTORNODE = 5;
  public int JJTANDNODE = 6;
  public int JJTBITWISEORNODE = 7;
  public int JJTBITWISEXORNODE = 8;
  public int JJTBITWISEANDNODE = 9;
  public int JJTEQNODE = 10;
  public int JJTNENODE = 11;
  public int JJTLTNODE = 12;
  public int JJTGTNODE = 13;
  public int JJTLENODE = 14;
  public int JJTGENODE = 15;
  public int JJTADDNODE = 16;
  public int JJTSUBTRACTNODE = 17;
  public int JJTMULNODE = 18;
  public int JJTDIVNODE = 19;
  public int JJTMODNODE = 20;
  public int JJTRSHIFTNODE = 21;
  public int JJTLSHIFTNODE = 22;
  public int JJTRROTNODE = 23;
  public int JJTLROTNODE = 24;
  public int JJTBITWISECOMPLNODE = 25;
  public int JJTNOTNODE = 26;
  public int JJTID = 27;
  public int JJTINTCONSTNODE = 28;
  public int JJTTRUENODE = 29;
  public int JJTFALSENODE = 30;
  public int JJTSHA256 = 31;
  public int JJTMD5 = 32;
  public int JJTBLOCK = 33;
  public int JJTSTATEMENTEXPRESSION = 34;
  public int JJTIFSTATEMENT = 35;
  public int JJTREPEATSTATEMENT = 36;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "InputSpecificationStatement",
    "VerifyStatement",
    "void",
    "Assignment",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "RShiftNode",
    "LShiftNode",
    "RRotNode",
    "LRotNode",
    "BitwiseComplNode",
    "NotNode",
    "Id",
    "IntConstNode",
    "TrueNode",
    "FalseNode",
    "SHA256",
    "MD5",
    "Block",
    "StatementExpression",
    "IfStatement",
    "RepeatStatement",
  };
}
/* JavaCC - OriginalChecksum=e82aacdbca2156567e5ea026a2eeb27b (do not edit this line) */
