package ElasticPL;
/* Generated By:JJTree&JavaCC: Do not edit this line. ElasticPLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ElasticPLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 6;
  /** RegularExpression Id. */
  int IDENTIFIER = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int NOZERODIGIT = 47;
  /** RegularExpression Id. */
  int ONE = 48;
  /** RegularExpression Id. */
  int TWO = 49;
  /** RegularExpression Id. */
  int ZEROTOFOUR = 50;
  /** RegularExpression Id. */
  int FIVE = 51;
  /** RegularExpression Id. */
  int ZEROTOFIVE = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "\"input\"",
    "\"verify\"",
    "\";\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">>\"",
    "\"<<\"",
    "\">>>\"",
    "\"<<<\"",
    "\"~\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\"SHA256\"",
    "\"MD5\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"repeat\"",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<NOZERODIGIT>",
    "<ONE>",
    "<TWO>",
    "<ZEROTOFOUR>",
    "<FIVE>",
    "<ZEROTOFIVE>",
  };

}
